name: cov

description: Very simple action to run code coverage checking for go projects.

inputs:
  main_branch:
    description: The main branch name.
    required: true
    default: main
  cov_version:
    description: The version to use for cov.
    required: true
    default: ${{github.action_ref}}
  cov_threshold:
    description: Default required coverage percentage.
    default: "90"
  cov_file:
    description: The name of the coverage file to use.
    required: true
    default: coverage.out

runs:
  using: 'composite'

  steps:
  - name: coverage
    shell: bash
    run: |
      go install github.com/PaloAltoNetworks/cov@${{inputs.cov_version}}

      echo "base_ref: ${{github.base_ref}}"
      echo "main_branch: ${{inputs.main_branch}}"

      if [[ "${{github.base_ref}}" == "${{inputs.main_branch}}" ]]; then
        git fetch origin ${{ github.base_ref }}
        export BRANCH_ARG="-b origin/${{github.base_ref}}"
      fi

      /home/runner/go/bin/cov $BRANCH_ARG \
          -t ${{inputs.cov_threshold}} \
          -e 0 \
          --send-status "${{github.repository}}@${{github.sha}}" \
          --send-token "${{github.token}}" \
          ${{inputs.cov_file}}
