name: cov

description: Very simple action to run code coverage checking for go projects.

inputs:
  main:
    description: The main branch name
    required: true
    default: master
  cov_version:
    description: The version to use for cov
    required: true
    default: master
  cov_threshold:
    description: Default required coverage percentage
    default: "70"
  cov_file:
    description: The name of the coverage file to use.
    required: true
    default: coverage.out

runs:
  using: 'composite'

  steps:
  - name: coverage
    shell: bash
    run: |
      go install github.com/PaloAltoNetworks/cov@${{inputs.cov_version}}

      if [[ "${{github.base_ref}}" == "${{inputs.main}}" ]]; then
        git fetch origin ${{ github.base_ref }}
        BRANCH_ARG="-b origin/${{github.base_ref}}"
      fi

      if ! /home/runner/go/bin/cov $BRANCH_ARG -t ${{inputs.cov_threshold}} ${{inputs.cov_file}}; then
        curl \
          -H "Authorization: Bearer ${{github.token}}" \
          -X POST https://api.github.com/repos/${{github.repository}}/statuses/${{github.sha}} \
          -d '{"state":"failure","description":"not up to standard","context":"cov"}'
        exit 1
      fi

      curl \
          -H "Authorization: Bearer ${{github.token}}" \
          -X POST https://api.github.com/repos/${{github.repository}}/statuses/${{github.sha}} \
          -d '{"state":"success","description":"up to standard","context":"cov"}'
      exit 0
