name: cov

description: Very simple action to run code coverage checking for go projects.

inputs:
  main_branch:
    description: The main branch name.
    required: true
    default: main
  cov_version:
    description: The version to use for cov.
    required: true
    default: ${{github.action_ref}}
  cov_threshold:
    description: Default required coverage percentage.
    default: "90"
  cov_file:
    description: The name of the coverage file to use.
    required: true
    default: coverage.out

runs:
  using: 'composite'

  steps:
  - name: coverage
    shell: bash
    run: |
      go install github.com/PaloAltoNetworks/cov@${{inputs.cov_version}}

      echo "* main_branch: ${{inputs.main_branch}}"
      echo "* cov_version: ${{inputs.cov_version}}"
      echo "* cov_threshold: ${{inputs.cov_threshold}}"
      echo "* cov_file: ${{inputs.cov_file}}"
      echo "* head_ref: ${{github.head_ref}}"
      echo "* base_ref: ${{github.base_ref}}"
      echo "* sha: ${{github.sha}}"

      if [[ "${{github.head_ref}}" != "" ]]; then
        if [[ "${{github.head_ref}}" != "${{inputs.base_ref}}" ]]; then
          echo "- pull request: fetching branch ${{github.base_ref}}"
          git fetch origin ${{ github.base_ref }}
          export BRANCH_ARG="-b origin/${{github.base_ref}}"
        fi
      fi

      set -x
      /home/runner/go/bin/cov $BRANCH_ARG \
          -e 0 \
          -t ${{inputs.cov_threshold}} \
          --send-status "${{github.repository}}@${{github.sha}}" \
          --send-token "${{github.token}}" \
          ${{inputs.cov_file}}
